### ISSUE TITLE
Consider switching from drf-yasg to drf-spectacular

### ISSUE THREAD

**Issue by kstypik** [Ewa-Anna/travel-planner#1]
drf-spectacular is a much better maintained library nowadays and supports generation of OpenAPI 3 (drf-yasg will probably forever stay on 2.0).

Excerpt from drf-yasg README:

> If you are looking to add Swagger/OpenAPI support to a new project you might want to take a look at [drf-spectacular](https://github.com/tfranzel/drf-spectacular), which is an actively maintained new library that shares most of the goals of this project, while working with OpenAPI 3.0 schemas.

> OpenAPI 3.0 provides a lot more flexibility than 2.0 in the types of API that can be described. drf-yasg is unlikely to soon, if ever, get support for OpenAPI 3.0.

Source: https://github.com/axnsan12/drf-yasg?tab=readme-ov-file#openapi-30-note

drf-spectacular - https://github.com/tfranzel/drf-spectacular

**Comment by Ewa-Anna** [comment]
Thank you for suggesting drf-spectacular. I'll definitely give it a try and see how it works out. 
Appreciate you bringing this to my attention!

**Comment by Ewa-Anna** [comment]
Pull request #2
